# Generated by Django 5.1.7 on 2025-04-08 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_management', '0005_remove_branch_manager_branchmanager_branch'),
        ('user_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='created_by_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to='main_management.branchmanager'),
        ),
    ]
