# Generated by Django 5.1.7 on 2025-04-14 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_authentication', '0002_customuser_created_by_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='created_by_manager',
        ),
    ]
