# Generated by Django 5.0.3 on 2025-03-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_rename_category_id_products_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
