# Generated by Django 5.1 on 2025-03-24 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_order_staff_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_item',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELED', 'Canceled')], default='CONFIRMED', max_length=128),
        ),
    ]
