# Generated by Django 5.1 on 2025-03-24 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_order_item_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_item',
            name='status',
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('CANCELED', 'Canceled')], default='CONFIRMED', max_length=128),
        ),
    ]
