# Generated by Django 5.1.7 on 2025-04-01 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branch_management', '0001_initial'),
        ('main_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchstaff',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_management.branch'),
        ),
    ]
