# Generated by Django 5.1.5 on 2025-03-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_remove_products_ingredients_products_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
