# Generated by Django 5.1.7 on 2025-04-04 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_management', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='branch',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
    ]
