# Generated by Django 5.1.7 on 2025-04-04 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_management', '0003_branch_email_branch_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchmanager',
            name='branch',
        ),
        migrations.AddField(
            model_name='branch',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='main_management.branchmanager'),
        ),
    ]
