# Generated by Django 5.1.7 on 2025-04-08 10:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_management', '0005_remove_branch_manager_branchmanager_branch'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchmanager',
            name='user',
        ),
        migrations.AddField(
            model_name='branchmanager',
            name='user',
            field=models.ManyToManyField(related_name='managers', to=settings.AUTH_USER_MODEL),
        ),
    ]
