# Generated by Django 5.1.7 on 2025-04-14 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_management', '0007_remove_branchmanager_user_branchmanager_user'),
        ('user_authentication', '0003_remove_customuser_created_by_manager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BranchManager',
        ),
    ]
