# Generated by Django 5.1.7 on 2025-04-02 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_management', '0003_initial'),
        ('main_management', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchstaff',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_management.branch'),
        ),
        migrations.AlterField(
            model_name='branchstaff',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='branchstaff', to=settings.AUTH_USER_MODEL),
        ),
    ]
