# Generated by Django 5.1.7 on 2025-04-12 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_management', '0004_alter_branchstaff_branch_alter_branchstaff_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branchstaff',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='branchstaff',
            name='name',
        ),
        migrations.RemoveField(
            model_name='branchstaff',
            name='surname',
        ),
        migrations.AddField(
            model_name='branchstaff',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
        migrations.AlterField(
            model_name='branchstaff',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='branchstaff',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff')], default='staff', max_length=128),
        ),
    ]
