# Generated by Django 5.1.7 on 2025-04-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_management', '0004_alter_branchstaff_branch_alter_branchstaff_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchstaff',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
