# Generated by Django 5.1.7 on 2025-04-06 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_management', '0005_rename_user_id_branchstaff_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchstaff',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='main_management.branch'),
        ),
    ]
