# Generated by Django 5.1.7 on 2025-04-06 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_management', '0005_alter_branchstaff_created'),
        ('main_management', '0005_remove_branch_manager_branchmanager_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branchstaff',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='branchstaff',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='main_management.branch'),
        ),
    ]
