# Generated by Django 5.1.7 on 2025-04-12 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('branch_management', '0005_alter_branchstaff_created'),
        ('branch_management', '0006_rename_user_id_branchstaff_user_and_more'),
    ]

    operations = [
    ]
