# Generated by Django 5.1.7 on 2025-04-14 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branch_management', '0007_merge_20250412_1537'),
        ('main_management', '0008_delete_branchmanager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchstaff',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branchstaff_branch', to='main_management.branch'),
        ),
    ]
